export const cities = [
  { value: "1273294", label: "Nairobi" },
  { value: "1261481", label: "Muranga" },
  { value: "1277333", label: "Kisumu" },
  { value: "1275004", label: "Mombasa" },
  { value: "1275339", label: "Nakuru" },
  { value: "1264527", label: "Nyeri" },
  { value: "1270642", label: "kericho" },
  { value: "1269843", label: "Kiambu" },
  { value: "1262180", label: "Machakos" },
  { value: "1273874", label: "Makueni" },
  { value: "1260086", label: "Bungoma" },
  { value: "1264728", label: "Nyamira" },
  { value: "1259229", label: "Nyandarua" },
  { value: "1258986", label: "Thika" },
  { value: "1279233", label: "Naivasha" },
  { value: "1271308", label: "Laikipia" },
  { value: "1255364", label: "Kirinyaga" },
  { value: "1267995", label: "Meru" },
  { value: "1269515", label: "Embu" },
  { value: "1256237", label: "Bomet" },
];
export const cropdata = [
  {
    "crop": {
      "name": "Rice",
      "qnt": "30"
    },
    "sold_at": 3200,
    "expense": {
      "seeds": 600,
      "fertilizers": [
        {
          "name": "DAP",
          "cost": 350
        },
        {
          "name": "Potash",
          "cost": 270
        }
      ],
      "electricity": 500,
      "machinery": 900,
      "labor": 600,
      "water_usage": 1100,
      "storage": 400,
      "transport": 500,
      "pesticides": [
        {
          "name": "Chlorpyrifos",
          "cost": 200
        }
      ]
    }
  },
  {
    "crop": {
      "name": "Barley",
      "qnt": "15"
    },
    "sold_at": 2100,
    "expense": {
      "seeds": 450,
      "fertilizers": [
        {
          "name": "Urea",
          "cost": 280
        },
        {
          "name": "Ammonium Nitrate",
          "cost": 300
        }
      ],
      "electricity": 450,
      "machinery": 850,
      "labor": 500,
      "water_usage": 1050,
      "storage": 300,
      "transport": 400,
      "pesticides": [
        {
          "name": "Malathion",
          "cost": 180
        }
      ]
    }
  },
  {
    "crop": {
      "name": "Maize",
      "qnt": "25"
    },
    "sold_at": 2900,
    "expense": {
      "seeds": 550,
      "fertilizers": [
        {
          "name": "NPK",
          "cost": 320
        },
        {
          "name": "Sulphate",
          "cost": 260
        }
      ],
      "electricity": 470,
      "machinery": 900,
      "labor": 620,
      "water_usage": 1150,
      "storage": 450,
      "transport": 420,
      "pesticides": [
        {
          "name": "Permethrin",
          "cost": 160
        }
      ]
    }
  },
  {
    "crop": {
      "name": "Soybean",
      "qnt": "18"
    },
    "sold_at": 3400,
    "expense": {
      "seeds": 650,
      "fertilizers": [
        {
          "name": "Phosphorus",
          "cost": 310
        },
        {
          "name": "Ammonium Sulfate",
          "cost": 290
        }
      ],
      "electricity": 490,
      "machinery": 920,
      "labor": 570,
      "water_usage": 1250,
      "storage": 380,
      "transport": 430,
      "pesticides": [
        {
          "name": "Cypermethrin",
          "cost": 175
        }
      ]
    }
  },
  {
    "crop": {
      "name": "Oats",
      "qnt": "20"
    },
    "sold_at": 2800,
    "expense": {
      "seeds": 500,
      "fertilizers": [
        {
          "name": "Nitrogen",
          "cost": 270
        },
        {
          "name": "Lime",
          "cost": 250
        }
      ],
      "electricity": 430,
      "machinery": 890,
      "labor": 560,
      "water_usage": 1120,
      "storage": 360,
      "transport": 410,
      "pesticides": [
        {
          "name": "Lambda-Cyhalothrin",
          "cost": 140
        }
      ]
    }
  }
];


export const countryCodes = [
  { code: "+1", country: "🇺🇸 United States" },
  { code: "+44", country: "🇬🇧 United Kingdom" },
  { code: "+91", country: "🇮🇳 India" },
  { code: "+86", country: "🇨🇳 China" },
  { code: "+81", country: "🇯🇵 Japan" },
  { code: "+49", country: "🇩🇪 Germany" },
  { code: "+33", country: "🇫🇷 France" },
  { code: "+39", country: "🇮🇹 Italy" },
  { code: "+7", country: "🇷🇺 Russia" },
  { code: "+55", country: "🇧🇷 Brazil" },
  { code: "+52", country: "🇲🇽 Mexico" },
  { code: "+34", country: "🇪🇸 Spain" },
  { code: "+61", country: "🇦🇺 Australia" },
  { code: "+1", country: "🇨🇦 Canada" },
  { code: "+82", country: "🇰🇷 South Korea" },
  { code: "+31", country: "🇳🇱 Netherlands" },
  { code: "+90", country: "🇹🇷 Turkey" },
  { code: "+46", country: "🇸🇪 Sweden" },
  { code: "+41", country: "🇨🇭 Switzerland" },
  { code: "+65", country: "🇸🇬 Singapore" },
  { code: "+27", country: "🇿🇦 South Africa" },
  { code: "+54", country: "🇦🇷 Argentina" },
  { code: "+20", country: "🇪🇬 Egypt" },
  { code: "+66", country: "🇹🇭 Thailand" },
  { code: "+92", country: "🇵🇰 Pakistan" },
  { code: "+62", country: "🇮🇩 Indonesia" },
  { code: "+84", country: "🇻🇳 Vietnam" },
  { code: "+60", country: "🇲🇾 Malaysia" },
  { code: "+63", country: "🇵🇭 Philippines" },
  { code: "+64", country: "🇳🇿 New Zealand" },
  { code: "+43", country: "🇦🇹 Austria" },
  { code: "+32", country: "🇧🇪 Belgium" },
  { code: "+45", country: "🇩🇰 Denmark" },
  { code: "+358", country: "🇫🇮 Finland" },
  { code: "+30", country: "🇬🇷 Greece" },
  { code: "+353", country: "🇮🇪 Ireland" },
  { code: "+972", country: "🇮🇱 Israel" },
  { code: "+47", country: "🇳🇴 Norway" },
  { code: "+351", country: "🇵🇹 Portugal" },
  { code: "+48", country: "🇵🇱 Poland" },
  { code: "+40", country: "🇷🇴 Romania" },
  { code: "+36", country: "🇭🇺 Hungary" },
  { code: "+420", country: "🇨🇿 Czech Republic" },
  { code: "+56", country: "🇨🇱 Chile" },
  { code: "+57", country: "🇨🇴 Colombia" },
  { code: "+58", country: "🇻🇪 Venezuela" },
  { code: "+51", country: "🇵🇪 Peru" },
  { code: "+971", country: "🇦🇪 United Arab Emirates" },
  { code: "+966", country: "🇸🇦 Saudi Arabia" },
  { code: "+98", country: "🇮🇷 Iran" },
  { code: "+880", country: "🇧🇩 Bangladesh" },
  { code: "+234", country: "🇳🇬 Nigeria" },
  { code: "+254", country: "🇰🇪 Kenya" },
  { code: "+380", country: "🇺🇦 Ukraine" },
  { code: "+359", country: "🇧🇬 Bulgaria" },
  { code: "+385", country: "🇭🇷 Croatia" },
  { code: "+381", country: "🇷🇸 Serbia" },
  { code: "+352", country: "🇱🇺 Luxembourg" },
  { code: "+356", country: "🇲🇹 Malta" },
  { code: "+354", country: "🇮🇸 Iceland" },
  { code: "+371", country: "🇱🇻 Latvia" },
  { code: "+370", country: "🇱🇹 Lithuania" },
  { code: "+372", country: "🇪🇪 Estonia" },
  { code: "+373", country: "🇲🇩 Moldova" },
  { code: "+377", country: "🇲🇨 Monaco" },
  { code: "+376", country: "🇦🇩 Andorra" },
  { code: "+423", country: "🇱🇮 Liechtenstein" },
  { code: "+386", country: "🇸🇮 Slovenia" },
  { code: "+421", country: "🇸🇰 Slovakia" },
  { code: "+598", country: "🇺🇾 Uruguay" },
  { code: "+593", country: "🇪🇨 Ecuador" },
  { code: "+503", country: "🇸🇻 El Salvador" },
  { code: "+502", country: "🇬🇹 Guatemala" },
  { code: "+504", country: "🇭🇳 Honduras" },
  { code: "+506", country: "🇨🇷 Costa Rica" },
  { code: "+507", country: "🇵🇦 Panama" },
  { code: "+595", country: "🇵🇾 Paraguay" },
  { code: "+591", country: "🇧🇴 Bolivia" },
  { code: "+962", country: "🇯🇴 Jordan" },
  { code: "+961", country: "🇱🇧 Lebanon" },
  { code: "+968", country: "🇴🇲 Oman" },
  { code: "+974", country: "🇶🇦 Qatar" },
  { code: "+965", country: "🇰🇼 Kuwait" },
  { code: "+973", country: "🇧🇭 Bahrain" },
  { code: "+994", country: "🇦🇿 Azerbaijan" },
  { code: "+995", country: "🇬🇪 Georgia" },
  { code: "+993", country: "🇹🇲 Turkmenistan" },
  { code: "+998", country: "🇺🇿 Uzbekistan" },
  { code: "+996", country: "🇰🇬 Kyrgyzstan" },
  { code: "+977", country: "🇳🇵 Nepal" },
  { code: "+94", country: "🇱🇰 Sri Lanka" },
  { code: "+95", country: "🇲🇲 Myanmar" },
  { code: "+855", country: "🇰🇭 Cambodia" },
  { code: "+856", country: "🇱🇦 Laos" },
  { code: "+976", country: "🇲🇳 Mongolia" },
  { code: "+850", country: "🇰🇵 North Korea" },
  { code: "+853", country: "🇲🇴 Macau" },
  { code: "+852", country: "🇭🇰 Hong Kong" },
  { code: "+886", country: "🇹🇼 Taiwan" },
  { code: "+673", country: "🇧🇳 Brunei" },
  { code: "+670", country: "🇹🇱 East Timor" },
  { code: "+675", country: "🇵🇬 Papua New Guinea" },
  { code: "+679", country: "🇫🇯 Fiji" },
  { code: "+687", country: "🇳🇨 New Caledonia" },
  { code: "+689", country: "🇵🇫 French Polynesia" },
];

export const district = [
 
  "CHANGAMWE",
"JOMVU",
"KISAUNI",
"LIKONI",
"MVITA",
"NYALI",
"KINANGO",
"LUNGA LUNGA",
"MSAMBWENI",
"MATUGA",
"GANZE",
"KALOLENI",
"KILIFI NORTH",
"KILIFI SOUTH",
"MAGARINI",
"MALINDI",
"RABAI",
"BURA",
"GALOLE",
"GARSEN",
"LAMU EAST",
"LAMU WEST",
"MWATATE",
"TAVETA",
"VOI",
"WUNDANYI",
"DAADAB",
"FAFI",
"GARISSA TOWNSHIP",
"HULUGHO",
"IJARA",
"LAGDERA",
"BALAMBALA",
"Eldas",
"TARBAJ",
"WAJIR EAST",
"WAJIR NORTH",
"WAJIR SOUTH",
"WAJIR WEST",
"BANISSA",
"LAFEY",
"MANDERA EAST",
"MANDERA NORTH",
"MANDERA SOUTH",
"MANDERA WEST",
"LAISAMIS",
"MOYALE",
"NORTH HORR",
"SAKU",
"ISIOLO",
"MERTI",
"Garbatulla",
"BUURI",
"IGEMBE CENTRAL",
"IGEMBE NORTH",
"IGEMBE SOUTH",
"IMENTI CENTRAL",
"IMENTI NORTH",
"IMENTI SOUTH",
"TIGANIA EAST",
"TIGANIA WEST",
"THARAKA NORTH",
"THARAKA SOUTH",
"CHUKA",
"IGAMBANG'OMBE",
"MAARA",
"CHIAKARIGA",
"MUTHAMBI",
"MANYATTA",
"MBEERE NORTH",
"MBEERE SOUTH",
"RUNYENJES",
"KITUI WEST",
"KITUI CENTRAL",
"KITUI RURAL",
"KITUI SOUTH",
"KITUI EAST",
"MWINGI NORTH",
"MWINGI WEST",
"MWINGI CENTRAL",
"KATHIANI",
"MACHAKOS TOWN",
"MASINGA",
"MATUNGULU",
"MAVOKO",
"MWALA",
"YATTA",
"KAITI",
"KIBWEZI WEST",
"KIBWEZI EAST",
"KILOME",
"MAKUENI",
"MBOONI",
"KINANGOP",
"KIPIPIRI",
"NDARAGWA",
"OL KALOU",
"OL JORO OROK",
"KIANI EAST",
"KIANI WEST",
"MATHIRA EAST",
"MATHIRA WEST",
"MUKURWEINI",
"NYERI TOWN",
"OTHEYA",
"TETU",
"KIRINYAGA CENTRAL",
"KIRINYAGA EAST",
"KIRINYAGA WEST",
"MWEA EAST",
"MWEA WEST",
"GATANGA",
"KAHURO",
"KANDARA",
"KANGEMA",
"KIGUMO",
"KIHARU",
"MATHIOYA",
"MURANG'A SOUTH",
"GATUNDU NORTH",
"GATUNDU SOUTH",
"GITHUNGURI",
"JUJA",
"KABETE",
"KIAMBAA",
"KIAMBU",
"KIKUYU",
"LIMURU",
"RUIRU",
"THIKA TOWN",
"LARI"
];

export const crop = [
  "Arcanut (Processed)",
  "Arecanut",
  "Arhar/Tur",
  "Atcanut (Raw)",
  "Bajra",
  "Banana",
  "Barley",
  "Beans & Mutter(Vegetable)",
  "Bhindi",
  "Bitter Gourd",
  "Black pepper",
  "Blackgram",
  "Bottle Gourd",
  "Brinjal",
  "Cabbage",
  "Cardamom",
  "Carrot",
  "Cashewnut",
  "Cashewnut Processed",
  "Cashewnut Raw",
  "Castor seed",
  "Citrus Fruit",
  "Coconut",
  "Coffee",
  "Cond-spcs other",
  "Coriander",
  "Cotton(lint)",
  "Cowpea(Lobia)",
  "Cucumber",
  "Drum Stick",
  "Dry chillies",
  "Dry ginger",
  "Garlic",
  "Ginger",
  "Gram",
  "Grapes",
  "Groundnut",
  "Guar seed",
  "Horse-gram",
  "Jack Fruit",
  "Jowar",
  "Jute",
  "Khesari",
  "Korra",
  "Lemon",
  "Linseed",
  "Maize",
  "Mango",
  "Masoor",
  "Mesta",
  "Moong(Green Gram)",
  "Moth",
  "Niger seed",
  "Oilseeds total",
  "Onion",
  "Orange",
  "Other  Rabi pulses",
  "Other Cereals & Millets",
  "Other Fresh Fruits",
  "Other Kharif pulses",
  "Other Vegetables",
  "Paddy",
  "Papaya",
  "Peas  (vegetable)",
  "Peas & beans (Pulses)",
  "Pineapple",
  "Pome Fruit",
  "Pome Granet",
  "Potato",
  "Pulses total",
  "Pump Kin",
  "Ragi",
  "Rapeseed &Mustard",
  "Redish",
  "Rice",
  "Rubber",
  "Safflower",
  "Samai",
  "Sannhamp",
  "Sapota",
  "Sesamum",
  "Small millets",
  "Snak Guard",
  "Soyabean",
  "Sugarcane",
  "Sunflower",
  "Sweet potato",
  "Tapioca",
  "Tea",
  "Tobacco",
  "Tomato",
  "Turmeric",
  "Turnip",
  "Urad",
  "Varagu",
  "Wheat",
  "other fibres",
  "other misc. pulses",
  "other oilseeds",
];

export const season = ["short rains", "long rains", "Summer",  "Winter"];

export const cropType = [
  "Barley",
  "Cotton",
  "Ground Nuts",
  "Maize",
  "Millets",
  "Oil seeds",
  "Paddy",
  "Pulses",
  "Sugarcane",
  "Tobacco",
  "Wheat",
];

export const soilType = ["Black", "Clayey", "Loamy", "Red", "Sandy"];
